### ISSUE TITLE
Export theme doesn't work; "No layers found"

### ISSUE THREAD

**Issue by esthor** [jan-dh/sketch-tailwind#12]
### Description
I have never used this plugin before.
When I run the export, the 'Sketch Tailwind' window pops up, but it it white, besides the "Sketch Tailwind" text.
There is an error toast message towards the bottom of the Sketch window that say "No layers found".
I've tried selecting the layers one-by-one, all, groups, and even nothing selected. All reproduces the same error.
I'm on the latest release of sketch-tailwind, and Sketch 64 (latest version of Sketch at the time of writing).

Am I doing something totally wrong, or 

### Steps to reproduce

1. Try to export anything with the plugin in Sketch 64.

### Additional info

- Sketch version: 64
- OS version: macOS 10.15.4

**Comment by ChenMorSays** [comment]
I'm having the same problem @jan-dh

**Comment by jan-dh** [comment]
As stated in the docs:
```
The plugin gets it's info from the Layer Styles and Text Styles.
```
Make sure your document has [Layer styles](https://www.sketch.com/docs/styling/#layer-styles) and/or [Text styles](https://www.sketch.com/docs/styling/#text-styles)
