### ISSUE TITLE
Declaring Utility Patterns with @apply

### ISSUE THREAD

**Issue by Bliepjes** [jan-dh/sketch-tailwind#2]
First of all, thanks for making this! 👋

This one is for the long run maybe, but declaring Utility Patterns with this would be nice for the way I use theming, and having nested libraries in Sketch that each are a single source of truth in itself.

In code I'm mostly using @apply in tailwind since my workflow in Sketch — using shared styles & font-styles — can be kept in sync this way, and easy enough for designers to follow along since how I build libraries in Sketch is identical. https://tailwindcss.com/docs/extracting-components/

In contrast to why they mention to use this in the first place — after the fact —, it's the first thing I show someone before the fact they start writing unmaintainable styles. Doing that directly from Sketch would be a great addition. 

A simple checkbox per style on export to add the @apply would suffice in the UI for now, but since nesting is important for that, getting @apply to work early on could be a 💩sandwich to begin with!

**Comment by jan-dh** [comment]
Hmmm, not quiet sure I get what you're asking for. Could you clarify a bit more please? It's my understanding that Tailwind 1.0 will have support for `@apply` with utility variants like "hover", or is this not related?

**Comment by Bliepjes** [comment]
Sorry if I'm confusing you, but @apply works really well for creating smaller parts in your styling, not just for "hover" since I break up component parts into single responsibility classes like  "button" so I can easily adjust styles. 

To my understanding, you have "more export options" on your roadmap, but that could mean other vendors, but where I think more styling options. Therefore the @apply would make sense to me, but I see if this is more of a sub-atomic solution (that works really well) to get the basics out of Sketch.

If so, no worries. Never started & closed two issues myself in a day 😂🖖

**Comment by jan-dh** [comment]
But if you import your exported `theme.js` in to you tailwind config you can use it in your `@apply` everywhere within your css? 🤷‍♂️
I'm still a bit confused with what exactly it is you are asking. Could you maybe provide a walkthrough step by step or some sort of visual that would make it clearer?  😕

**Comment by jan-dh** [comment]
I'm going to close this for now. If you have more input, let me know.
