### ISSUE TITLE
Abandoned? Should I request the Tailwindcss beta 4?

### ISSUE THREAD

**Issue by miguelgargallo** [jan-dh/sketch-tailwind#41]
Abandoned? Should I request the Tailwindcss beta 4?

**Comment by jan-dh** [comment]
Hi there,

This isn't being maintained anymore no. As stated in the Readme:

> Note: This plugin will not be updated. I don't own a Sketch licence anymore and plugin development for Sketch is a bit of a pain tbh. Have made a Figma version of this plugin, you can find it over [here](https://www.figma.com/c/plugin/785619431629077634/Figma-Tailwindcss). That version is still being maintained and input for new features is welcome in the [repo](https://github.com/jan-dh/figma-tailwindcss/).
