### ISSUE TITLE
TailwindCSS 1.0.0 released, config file has changed

### ISSUE THREAD

**Issue by CurtisBelt** [jan-dh/sketch-tailwind#5]
They have very detailed docs for what has changed :+1: 

https://tailwindcss.com/docs/upgrading-to-v1

**Comment by jan-dh** [comment]
Ah, good catch. I'll test a bit and see if I can get everything updated for 1.0. Did you try importing the current styles in a v1. theme? Should work I believe.

**Comment by jan-dh** [comment]
@CurtisBelt did test this with the new Tailwind config, works as before.
