### ISSUE TITLE
Plugin sometimes works

### ISSUE THREAD

**Issue by ryankauk** [jan-dh/sketch-tailwind#6]
Hey, found this plugin, would really love to use it but it seems a bit flaky. When I open up a new project it works, if I open up a file that my designer already created the popup doesn't event show up.

**Comment by jan-dh** [comment]
Can you provide me with some more info so I can look to debug this? One of the files that don't work would be very nice. Also specific version of sketch would be handy.

**Comment by GFargo** [comment]
Was seeing similar issues when opening up a sketch file from a designer.  Ended up opening up  Sketch `Plugin Dev Tools` and noticed there are a couple JS warnings/errors occuring in the `get-state.js` file.

specifically the error that seems to break things is here for me https://github.com/jan-dh/sketch-tailwind/blob/master/src/get-state.js#L20

The script is trying to access layer styles, however in the current document I'm working within there are no `fills` defined.  This breaks script execution preventing the plugin from working.  Some error handling would go a long way in making this plugin more resilient to different sketch file configs.

**Comment by jan-dh** [comment]
Thanks for the input @GFargo. I haven't been working on the plugin since the initial release since the plugin development for Sketch is quiet cumbersome. I'm accepting PR's and I'm planing to take this up for a bit of a rewrite in the near future. Any input on features etc. like posted above are more then welcome.

**Comment by jan-dh** [comment]
I updated the plugin. Will be a while since the update pops up on the store, but you should be able to download the zip and update it that way. Issues should be solved, but feel free to reopen if that would not be the case.
