### ISSUE TITLE
Not working in OS Catalina

### ISSUE THREAD

**Issue by Ale-Alpha** [jan-dh/sketch-tailwind#7]
Trying to export theme in my sketch project but nothing happens and after a few seconds Sketch crashes down.
![Schermata 2019-10-29 alle 09 38 36](https://user-images.githubusercontent.com/32481735/67750653-e68e4080-fa2f-11e9-99ce-ee4a8606f1c8.png)
![Schermata 2019-10-29 alle 09 39 44](https://user-images.githubusercontent.com/32481735/67750749-1ccbc000-fa30-11e9-992d-261acd58692a.png)

**Comment by Ale-Alpha** [comment]
![Schermata 2019-10-29 alle 09 39 44](https://user-images.githubusercontent.com/32481735/67750717-10476780-fa30-11e9-9fc8-ac32373bf21a.png)

**Comment by jan-dh** [comment]
I'll try updating to Catalina this weekend and take it for a spin. Thanks for reporting this.

**Comment by jan-dh** [comment]
I just released an update with some bugfixes. It will take a bit before you can update it from the store, but you should be able to download it and test it.
