### ISSUE TITLE
Doesn't get confirmation message

### ISSUE THREAD

**Issue by abinashmohanty** [jan-dh/sketch-tailwind#8]
No doubt it's an amazing plugin, but when I tried to export, nothing happens as in no modal screen, no notification, etc. Am I doing anything wrong?

**Comment by jan-dh** [comment]
As mentioned (here) [https://github.com/jan-dh/sketch-tailwind/issues/7] this plugin could do with some better error handling and I haven't found the time to test it on Catalina. Busy times, but I will try and find some time to do a bit of a rewrite.

In the meantime, the more info I have the better. So:
- What version of Sketch
- What version of OS
- Do you see any errors (try using https://github.com/skpm/sketch-dev-tools for error logs)

**Comment by abinashmohanty** [comment]
Thanks @jan-dh I'm using the following specs.

- Sketch 59.1 (86144)
- mac mojave 10.14.6

**Comment by jan-dh** [comment]
@abinashmohanty I just released an update that should fix this issue. Feel free to reopen this if the issue persists
